CREATE TABLE Posts
(
PostID BIGINT AUTO_INCREMENT,
post VARCHAR(300),
UserID VARCHAR(30) NULL,
Tag VARCHAR(30),
dateinsert timestamp DEFAULT CURRENT_TIMESTAMP,
karma BIGINT default 0,
PRIMARY KEY (PostID));